#include <string.h>
#include <stdio.h>

#include "../accupos/accupos.h"

char *my_ass = "[Script Info]\n"
               "; Script generated by Aegisub 9530-cibuilds-79a0655eb\n"
               "; http://www.aegisub.org/\n"
               "Title: Default Aegisub file\n"
               "ScriptType: v4.00+\n"
               "WrapStyle: 0\n"
               "ScaledBorderAndShadow: yes\n"
               "YCbCr Matrix: None\n"
               "PlayResX: 1920\n"
               "PlayResY: 1080\n"
               "\n"
               "[Aegisub Project Garbage]\n"
               "Last Style Storage: ipid-我的样式-v3-双描边\n"
               "Video File: ?dummy:30.000000:300:1920:1080:154:154:154:\n"
               "Video AR Value: 1.777778\n"
               "Video Zoom Percent: 0.500000\n"
               "Active Line: 9\n"
               "\n"
               "[V4+ Styles]\n"
               "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
               "Style: 全局阴影-furigana,方正FW筑紫A圆 简 E,46,&H00FFFFFF,&H00FFFFFF,&H00FFFFFF,&H96727272,0,0,0,0,100,100,0,0,1,4.5,6.5,2,10,10,70,1\n"
               "Style: 星-米女芽衣-薮岛朱音-furigana,方正FW筑紫A圆 简 E,46,&H003535FF,&H003535FF,&H00FFFFFF,&H207677FF,0,0,0,0,100,100,0,0,1,4.5,4,2,10,10,70,1\n"
               "Style: 星-樱小路希奈子-铃原希实-furigana,方正FW筑紫A圆 简 E,46,&H00009FD4,&H000E95C1,&H00FFFFFF,&H0054C4D5,0,0,0,0,100,100,0,0,1,4.5,4,2,10,10,70,1\n"
               "Style: 星-恋-渚-furigana,方正FW筑紫A圆 简 E,46,&H00B9110A,&H00B62E21,&H00FFFFFF,&H00D26765,0,0,0,0,100,100,0,0,1,4.5,4,2,10,10,70,1\n"
               "Style: 星-堇-Pay-furigana,方正FW筑紫A圆 简 E,46,&H0000AB39,&H001EAA4D,&H00FFFFFF,&H5093FF9E,0,0,0,0,100,100,0,0,1,4.5,4,2,10,10,70,1\n"
               "Style: 星-可可-鲤鱼-furigana,方正FW筑紫A圆 简 E,46,&H009CA601,&H00A1AC08,&H00FFFFFF,&H50EBF793,0,0,0,0,100,100,0,0,1,4.5,4,2,10,10,70,1\n"
               "Style: 星-千-Nako-furigana,方正FW筑紫A圆 简 E,46,&H009158FB,&H009359EA,&H00FFFFFF,&H20BF99FF,0,0,0,0,100,100,0,0,1,4.5,4,2,10,10,70,1\n"
               "Style: 星-千-Nako,方正FW筑紫A圆 简 E,92,&H009158FB,&H009359EA,&H00FFFFFF,&H20BF99FF,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 星-可可-鲤鱼,方正FW筑紫A圆 简 E,92,&H009CA601,&H00A1AC08,&H00FFFFFF,&H50EBF793,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 星-堇-Pay,方正FW筑紫A圆 简 E,92,&H0000AB39,&H001EAA4D,&H00FFFFFF,&H5093FF9E,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 星-恋-渚,方正FW筑紫A圆 简 E,92,&H00B9110A,&H00B62E21,&H00FFFFFF,&H00D26765,0,0,0,0,100,100,0,0,1,9,20,2,10,10,70,1\n"
               "Style: 星-樱小路希奈子-铃原希实,方正FW筑紫A圆 简 E,92,&H00009FD4,&H000E95C1,&H00FFFFFF,&H0054C4D5,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 星-米女芽衣-薮岛朱音,方正FW筑紫A圆 简 E,92,&H003535FF,&H003535FF,&H00FFFFFF,&H207677FF,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 全局阴影,方正FW筑紫A圆 简 E,92,&H00FFFFFF,&H00FFFFFF,&H00FFFFFF,&H96727272,0,0,0,0,100,100,0,0,1,9,13,2,10,10,70,1\n"
               "Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n"
               "Style: 虹-岚珠-菜宝,方正FW筑紫A圆 简 E,92,&H00656DFF,&H00737AFE,&H00FFFFFF,&H00B8B7EE,0,0,0,0,100,100,0,0,1,9,8,2,10,10,60,1\n"
               "Style: 虹-果林-miyu碳,方正FW筑紫A圆 简 E,92,&H00C65E48,&H00C65E48,&H00FFFFFF,&H00FAA275,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 虹-栞子-萌P,方正FW筑紫A圆 简 E,92,&H007DAB34,&H006FA51D,&H00FFFFFF,&H0083CD70,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 虹-步梦-阿兔嘭,方正FW筑紫A圆 简 E,92,&H008A53FC,&H008A53FC,&H00FFFFFF,&H009994FF,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "Style: 虹-爱-奈酱,方正FW筑紫A圆 简 E,92,&H000058FF,&H000058FF,&H00FFFFFF,&H008D8DFF,0,0,0,0,100,100,0,0,1,9,8,2,10,10,70,1\n"
               "\n"
               "[Events]\n"
               "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
               "Comment: 0,0:00:00.00,0:00:00.01,Default,,0,0,0,template line all keeptags,!relayer(0)!!restyle('全局阴影')!{\\1a&HFF&\\3a&HFF&}\n"
               "Comment: 0,0:00:00.00,0:00:00.01,Default,,0,0,0,template line all keeptags,!relayer(1)!{\\bord11.5\\shad5.5\\3c!_G.interpolate_color(0.8,'&HFFFFFF&',line.styleref.color2)!\\1a&HFF&\\lhd-6}\n"
               "Comment: 0,0:00:00.00,0:00:00.01,Default,,0,0,0,template line all keeptags,!relayer(2)!{\\shad0}\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,星-恋-渚,,0,0,0,karaoke,{}我爱你，我的岬，我的岬，我的天堂 4(1)\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,星-米女芽衣-薮岛朱音,,0,0,0,karaoke,{}我爱你，我的岬，我的岬，我的天堂 5(2)\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,星-堇-Pay,,0,0,0,karaoke,{}我爱你，我的岬，我的岬，我的天堂 6(3)\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,星-恋-渚,,0,0,0,karaoke,{\\an9}我爱你，我的岬，我的岬，我的天堂 7(4)\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,星-可可-鲤鱼,,0,0,0,karaoke,{\\an8}wefewgreergrfw 8(5)\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,星-米女芽衣-薮岛朱音,,0,0,0,karaoke,{\\an9}我爱你，我的岬，我的岬，我的天堂 9(6)\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,虹-岚珠-菜宝,,0,0,0,karaoke,{\\an6}我爱你，我的岬，我的岬，我的天堂 10(7)\n"
               "Dialogue: 0,0:00:00.00,0:00:05.00,虹-岚珠-菜宝,,0,0,0,karaoke,{\\an6}我爱你，我的岬，我的岬，我的天堂 10(7)";

int main(void) {
    Accupos_Library *accupos = accupos_init(1920, 1080, my_ass, (int32_t) strlen(my_ass));

    for (int i = 0; i < accupos->n_dialogues; i++) {
        Accupos_Dialogue *dialogue = &accupos->dialogues[i];

        printf(
            "#%d: <%s>, pos_x = %d, pos_y = %d, width = %d, height = %d\n",
            i + 1,
            dialogue->text,
            dialogue->pos_x,
            dialogue->pos_y,
            dialogue->width,
            dialogue->height
        );
    }

    accupos_done(accupos);

    return 0;
}
